
-   name: Copy krb5.conf
    action: copy src=${managed_file_dir}/common/krb5.conf dest=/etc/krb5.conf owner=root group=root mode=0644

-   name: Install needed krb5 packages
    action: yum name=$item state=latest
    with_items:
        - krb5-workstation



