######################################
#

# Really need a module for authconfig
#- name: Password algorithm needs to be sha512
#  action: command /usr/sbin/authconfig --passalgo=sha512 --update

- name: Root password hash
  action:  user name=root password=$server_root_password 
