---

- name: Copy the gdm configuration tool into place
  action: >
    copy src=${managed_file_dir}/econscripts/gdm_settings.sh 
    dest=/etc/econ/gdm_settings.sh owner=root group=root mode=0755

- name: Check gdm configuration
  action: command /etc/econ/gdm_settings.sh status
  register: gdm_configured

- name: If needed, update system auth configuration
  action: command /etc/econ/econ_auth_config_tool.sh set_config
  only_if: "'${gdm_configured.stdout}' == 'FALSE'"

